### PR TITLE
Fixing Issue 75

### PR DESCRIPTION
**Pull request by thirtytwobits**
1. Fixing a real bug I found but not the same one that @pavel-kirienko
reported initially. Please advise.
2. Fixing some borked links.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
1. The filter `to_template_unique_name` is malfunctioning here. Below is an example of misgenerated code where unique identifiers are not unique:

```python
    @staticmethod
    def _deserialize_aligned_(_des_: Heartbeat_1_0._DeserializerTypeVar_) -> Heartbeat_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not byte-aligned'
        _bit_length_base_ = _des_.consumed_bit_length
        _des_.require_remaining_bit_length(56)
        # BEGIN COMPOSITE DESERIALIZATION: uavcan.node.Heartbeat.1.0
        # BEGIN STRUCTURE FIELD DESERIALIZATION: saturated uint32 uptime
        # The temporary _f0_ holds the value of the field "uptime"
        _des_.require_remaining_bit_length(32)
        assert _des_.consumed_bit_length % 8 == 0, 'saturated uint32'
        _f0_ = _des_.fetch_aligned_u32()
        # END STRUCTURE FIELD DESERIALIZATION: saturated uint32 uptime
        # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint2 health
        # The temporary _f0_ holds the value of the field "health"
        _des_.require_remaining_bit_length(2)
        assert _des_.consumed_bit_length % 8 == 0, 'truncated uint2'
        _f0_ = _des_.fetch_aligned_unsigned(2)
        # END STRUCTURE FIELD DESERIALIZATION: truncated uint2 health
        # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint3 mode
        # The temporary _f0_ holds the value of the field "mode"
        _des_.require_remaining_bit_length(3)
        _f0_ = _des_.fetch_unaligned_unsigned(3)
        # END STRUCTURE FIELD DESERIALIZATION: truncated uint3 mode
        # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint19 vendor_specific_status_code
        # The temporary _f0_ holds the value of the field "vendor_specific_status_code"
        _des_.require_remaining_bit_length(19)
        _f0_ = _des_.fetch_unaligned_unsigned(19)
        # END STRUCTURE FIELD DESERIALIZATION: truncated uint19 vendor_specific_status_code
        self = Heartbeat_1_0(uptime=_f0_,
                             health=_f0_,
                             mode=_f0_,
                             vendor_specific_status_code=_f0_)
```

2. Problem #75 is still there: `{{ t|full_reference_name|id }}` yields `uavcanZX002EnodeZX002EExecuteCommand_1_0`

**Comment by pavel-kirienko** [comment]
I am testing this against https://github.com/UAVCAN/pyuavcan/tree/nunavut-updates with Nunavut installed from sources via `./setup.py install`

**Comment by thirtytwobits** [comment]
> 1. The filter `to_template_unique_name` is malfunctioning here. Below is an example of misgenerated code where unique identifiers are not unique:
> 
> ```python
>     @staticmethod
>     def _deserialize_aligned_(_des_: Heartbeat_1_0._DeserializerTypeVar_) -> Heartbeat_1_0:
>         assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not byte-aligned'
>         _bit_length_base_ = _des_.consumed_bit_length
>         _des_.require_remaining_bit_length(56)
>         # BEGIN COMPOSITE DESERIALIZATION: uavcan.node.Heartbeat.1.0
>         # BEGIN STRUCTURE FIELD DESERIALIZATION: saturated uint32 uptime
>         # The temporary _f0_ holds the value of the field "uptime"
>         _des_.require_remaining_bit_length(32)
>         assert _des_.consumed_bit_length % 8 == 0, 'saturated uint32'
>         _f0_ = _des_.fetch_aligned_u32()
>         # END STRUCTURE FIELD DESERIALIZATION: saturated uint32 uptime
>         # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint2 health
>         # The temporary _f0_ holds the value of the field "health"
>         _des_.require_remaining_bit_length(2)
>         assert _des_.consumed_bit_length % 8 == 0, 'truncated uint2'
>         _f0_ = _des_.fetch_aligned_unsigned(2)
>         # END STRUCTURE FIELD DESERIALIZATION: truncated uint2 health
>         # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint3 mode
>         # The temporary _f0_ holds the value of the field "mode"
>         _des_.require_remaining_bit_length(3)
>         _f0_ = _des_.fetch_unaligned_unsigned(3)
>         # END STRUCTURE FIELD DESERIALIZATION: truncated uint3 mode
>         # BEGIN STRUCTURE FIELD DESERIALIZATION: truncated uint19 vendor_specific_status_code
>         # The temporary _f0_ holds the value of the field "vendor_specific_status_code"
>         _des_.require_remaining_bit_length(19)
>         _f0_ = _des_.fetch_unaligned_unsigned(19)
>         # END STRUCTURE FIELD DESERIALIZATION: truncated uint19 vendor_specific_status_code
>         self = Heartbeat_1_0(uptime=_f0_,
>                              health=_f0_,
>                              mode=_f0_,
>                              vendor_specific_status_code=_f0_)
> ```
> 
> 1. Problem #75 is still there: `{{ t|full_reference_name|id }}` yields `uavcanZX002EnodeZX002EExecuteCommand_1_0`

Right you have to use the new filter `ns_id`

**Comment by thirtytwobits** [comment]
> I would prefer to have just one `id` for everything

The problem is the correct behaviour changes based on context. If you want a string to be a valid identifier then the current `id` filter is pedantically correct. What I think you want is the ability to create a token separated list of valid identifiers. You can either do this using split and join yourself, I can create the new `ns_id` filter as proposed here, or I could provide a "for token in string" filter instead. For example:

```
{{ myobj.full_name | for_each_token(sep='.') | id }}
```

This filter would be language agnostic which is nice but it's less concise then:

```
{{ myobj.full_name | ns_id }}
```

The only other solution requires the id filter to know the context which would require Nunavut to actually lex the source being generated and adapt in a second expansion of the template. This would not be trivial.

**Comment by pavel-kirienko** [comment]
Okay. Maybe a better solution is then to modify `full_reference_name` and `short_reference_name` to emit stropped ids?

**Pull request merged**
