### PR TITLE
Fixes for pydsdl changes

### PR DESCRIPTION
**Pull request by thirtytwobits**
We've changed both the requirement to have either @sealed or @extent and how we treat service types.

This fixes issue #152  and #153

### CODE REVIEW

**Review by pavel-kirienko — APPROVED** [review]
It's interesting that you treat service types as namespaces here. Maybe it makes sense. In the future, we may change the spec to make request/response types reachable (make them non-Voldemort), in which case having the version number attached directly to the type rather than its parent would be sensible. PyDSDL is indifferent to this because it guarantees that request/response share metadata like version, deprecation status, source file path, etc. with their parent service type.

**Comment by thirtytwobits** [comment]
> It's interesting that you treat service types as namespaces here. Maybe it makes sense. In the future, we may change the spec to make request/response types reachable (make them non-Voldemort), in which case having the version number attached directly to the type rather than its parent would be sensible. PyDSDL is indifferent to this because it guarantees that request/response share metadata like version, deprecation status, source file path, etc. with their parent service type.

Hmm. now I wonder if I'm doing the right thing here? I suppose I can restore the old behavior using the assumption that the request and response type's version is always the same as the parent service type and that the parent's name is the namespace part that contains the request and response types. Do you think that `foo_BarService_1_0_Request` is actually more correct then `foo_BarService_Response_1_0`? The nice thing about the way I was doing it before was the short references were `BarService_1_0_Request` instead of `Request_1_0`. The former created more descriptive names then the latter, obviously.

**Comment by pavel-kirienko** [comment]
As per the current Spec, if you look hard enough, the correct approach is to say `BarService_1_0`, then `Request`, but the Spec doesn't *require* this, it never even touches this question because it is not relevant for wire interoperability. If we look into the future, then it is more likely (as I see things) that we will be converging towards `Request_1_0`.

> The nice thing about the way I was doing it before was the short references were BarService_1_0_Request instead of Request_1_0. The former created more descriptive names then the latter, obviously.

Meh, I don't think it matters at all. PyUAVCAN says just `Request`, not even mentioning the version numbers. In the end, there will always be a risk of collision if you use the short name only.

**Comment by thirtytwobits** [comment]
Hmm. I think my error is actually that I'm generating named types for Request and Response instead of making them anonymous struts in a concrete service struct. The logic in this CR is correct then but it shouldn't be possible to actually generate types for Request and Response. Do you think I should open an issue against that?

**Pull request merged**
