### PR TITLE
Bump patch version to fix CD

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Address https://github.com/UAVCAN/nunavut/pull/202#issuecomment-879699434

### CODE REVIEW

**Comment by thirtytwobits** [comment]
Gaa. Sorry. My bad. I should have caught this.

**Comment by pavel-kirienko** [comment]
@thirtytwobits I think Buildkite is malfunctioning

**Comment by thirtytwobits** [comment]
On it. Sorry.

**Comment by thirtytwobits** [comment]
This isn't needed any more.

**Pull request closed without merging**
