### PR TITLE
Improvements to the native build instructions for contributors

### PR DESCRIPTION
**Pull request by thirtytwobits**
Added instructions for manually building native verification tests and added support for environment variables in the CMakeLists.txt

### CODE REVIEW

**Comment by thirtytwobits** [comment]
@PetervdPerk-NXP , The fix I pushed yesterday does support the pydsdl changes. Please rebase/pull that change from the issue/115 branch and try again. This PR provides (hopefully) better instructions for manually building the verification tests.

**Review by TSC21 — APPROVED** [review]
This is good!

**Comment by thirtytwobits** [comment]
Paging @davidlenfesty and @PetervdPerk-NXP : try these instructions and let me know they work for you.

**Comment by davidlenfesty** [comment]
Big note, it doesn't seem to work if you install tox and run the initial environment setup from inside of a venv.

Installing it system wide worked right away though.

**Pull request merged**
